### ISSUE TITLE
eeprom address wrong for emissivity

### ISSUE THREAD

**Issue by vintan** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#1]
AccessEEPROM  is 0x13 you have written, but it is 0x03

**Comment by lanselambor** [comment]
Hi vintan, on which platform did you tried?

**Comment by lanselambor** [comment]
Hey vintan, I've received your email, you can refer to our product wiki for more information, that may do you a favor.
http://www.seeedstudio.com/wiki/Grove_-_Digital_Infrared_Temperature_Sensor

**Comment by vintan** [comment]
I have tried with Arduino

**Comment by vintan** [comment]
Reffer the datasheet in seedstudio wiki, page number 9 - section 8.3.3
