### ISSUE TITLE
This doesn't support the new ARM based arduino boards

### ISSUE THREAD

**Issue by kyle-visner** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#10]
Hi, trying to use this library with an Arduino mkr wan 1300, but the I2CMaster library doesn't support ARM based boards.  Even if you try to use it in wire mode, it still tries to include the I2CMaster library and causes a build error.

**Comment by Pillar1989** [comment]
We added CI to find these unsupported exception platforms, and we're working on them.
