### ISSUE TITLE
How can I use this on a Raspberry Pi ?

### ISSUE THREAD

**Issue by WirthmU** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#12]
I would want do use it on a RPI4 using the GrovePi Hat

**Comment by Pillar1989** [comment]
https://github.com/CRImier/python-MLX90614，  It's already been done, and the code is relatively simple.

**Comment by Lesords** [comment]
Hello,

I'm going to close this issue, feel free to re-open it if you have any other questions.
