### ISSUE TITLE
MLX90615 Temperature Accuracy

### ISSUE THREAD

**Issue by micryst** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#13]
i am using MLX90615 Sensor to measure the body temperature of Human with Emissivity value 0.98.
MLX90615 is connected to ATMEGA328P.
Body distance from the sensor is around 2-3 CM while measuring Temperature .
i compare the Temperature given by MLX90615 sensor with Infrared Temperature Sensor Which Is Available In Market. 
But there is a difference of 2-3 degree Celsius.  MLX90615 giving 2-3 degree Celsius  lower than Infrared Temperature Sensor reading.

So Please suggest me to how i can achieve more accurate reading of MLX90615.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
