### ISSUE TITLE
#error unknown CPU on ESP32

### ISSUE THREAD

**Issue by dragg96** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#14]
How to fix #error unknown CPU using ESP32  ?

**Comment by Lesords** [comment]
Hello,

I'm sorry it took me so long to reply to you. 

This is indeed a problem at the moment and I will deal with this as soon as possible

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
