### ISSUE TITLE
Voltage levels

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#3]
AFAIK the MLX90615 is a 3V rated device, but this software make no mention of this, and the Arduino devices supported are 5V devices. This would appear to be a recipe for disaster.  What am I missing please?

**Comment by Pillar1989** [comment]
I'm sorry that I didn't have time to deal with your problem. This issue is closed first. If you still need to discuss, you can reopen it, and we will try our best to help you
