### ISSUE TITLE
Due support

### ISSUE THREAD

**Issue by White-Rabbit-Scientific** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#4]
I am wondering about whether you could add support for the Arduino Due?  Presently it fails to compile for Due processors.

**Comment by superyarik** [comment]
also request this, how define variables for this unknown CPU?

**Comment by pushmeaway2** [comment]
Same here... i followed the seeedstudio tzutorial but get an #unknown cpu error 
[(http://wiki.seeedstudio.com/Grove-Digital_Infrared_Temperature_Sensor/#hardware)]
.
Can anybody help please? I'm using the Grove Base Shield and the Seeeduino 4.2

I'm guessing the i2cMaster.h has to be updated as it brings the error:

/**
 * \class TwiMaster
 * \brief Hardware I2C master class
 *
 * Uses ATmega TWI hardware port
 */
class TwiMaster : public I2cMasterBase {
 public:
  explicit TwiMaster(bool enablePullup);
  uint8_t read(uint8_t last);
  bool restart(uint8_t addressRW);
  bool start(uint8_t addressRW);
  /** \return status from last TWI command - useful for library debug */
  #if defined(ARDUINO_ARCH_AVR)
  uint8_t status(void) {return status_;}
  #endif
  void stop(void);
  bool write(uint8_t data);
 private:
  TwiMaster() {}

  #if defined(ARDUINO_ARCH_AVR)

  uint8_t status_;
  void execCmd(uint8_t cmdReg);

  #elif defined(ARDUINO_ARCH_ESP8266)

  uint8_t addressRW_ = 0;

  #else
  **#error unknown CPU**
  #endif
};
#endif  // I2C_MASTER_H

**Comment by KillingJacky** [comment]
@pushmeaway2 the tutorial's instructing to use the soft i2c, why could you encounter the unknown CPU error? To have the I2cMaster library support Arduino Due, it's not just as simple as adding some varibles in I2cMaster.h, the interrupt mechanism is different from that of AVR chips, it seems that I2cMaster library has no plan to support Arduino Due since the Due's user volume. So please consider using the soft i2c.

**Comment by lanselambor** [comment]
@pushmeaway2 has fixed Seeeduino 4.2  compilation error "error unknown CPU" by adding ARDUINO_ARCH_AVR  to the board library, please update Seeeduino 4.2 board library.

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
