### ISSUE TITLE
Changing I2C address in EEPROM

### ISSUE THREAD

**Issue by curtpw** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#7]
Hello, I'm having trouble changing the I2C/SMBus address in EEPROM. This would be an extremely useful thing to have documented. Over a hundred MLX90615 sensors can be used on the same bus with this feature.

I assume I need to make use of the following function:   writeEEPROM()

Would you mind providing guidance?

**Comment by Pillar1989** [comment]
I'm sorry that I didn't have time to deal with your problem. This issue is closed first. If you still need to discuss, you can reopen it, and we will try our best to help you
