### ISSUE TITLE
Using with ESP32

### ISSUE THREAD

**Issue by ziatajo** [Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615#8]
HI,

How can I use this library with an ESP32 (Adafruit Feather). I always get an "unknown CPU" error within the I2cMaster.h
Can you help me?

Thank you!

**Comment by Pillar1989** [comment]
I'm sorry that I didn't have time to deal with your problem. This issue is closed first. If you still need to discuss, you can reopen it, and we will try our best to help you
